export const seedBooks = [
  {
    title: 'Persistent value-added system engine',
    authors: ['Brian Jensen'],
    ISBN: '978-0-1706733911-23709-9',
    publishers: ['Lester, Cameron and Brown', 'Jones Group'],
    quantityAvailable: 22,
    price: 264158,
    summary:
      'Near tax help role represent success. Everything his indicate month consider.',
    averageRating: 3.8,
    genres: ['Sword and Sorcery', 'Mystery'],
    reviews: ['Attention stuff threat culture.'],
  },
  {
    title: 'Implemented neutral superstructure',
    authors: ['Dr. Melissa Duran MD', 'Charles Kramer'],
    ISBN: '978-0-1706733911-50455-9',
    publishers: ['Ryan-Lawson'],
    quantityAvailable: 16,
    price: 853864,
    summary: 'Network including option eye method. And enjoy within blue.',
    averageRating: 4.2,
    genres: ['Supernatural Horror', 'Science Fiction'],
    reviews: [
      'Surface role front carry early health.',
      'Maintain together general fall several.',
      'Forget community little do.',
    ],
  },
  {
    title: 'Stand-alone human-resource portal',
    authors: ['Peter Jordan', 'Erin Ruiz'],
    ISBN: '978-0-1706733911-46255-9',
    publishers: ['Martin PLC', 'Baker Ltd'],
    quantityAvailable: 42,
    price: 541103,
    summary:
      'Politics democratic director address radio develop. Anyone bit power Mr leader fish. Land performance watch then new.',
    averageRating: 3.3,
    genres: ['Mystery', 'Gothic Horror', 'Psychological Horror'],
    reviews: ['Manage available radio research play light.'],
  },
  {
    title: 'Multi-channeled multi-tasking portal',
    authors: ['Bryan Campbell'],
    ISBN: '978-0-1706733911-42544-9',
    publishers: ['Lee-Moreno', 'Sandoval Inc'],
    quantityAvailable: 25,
    price: 895792,
    summary:
      'Nice reflect building respond image technology effect. Race product cut military result ability.',
    averageRating: 3.9,
    genres: ['Crime'],
    reviews: [
      'Military order say road scientist network.',
      'Professional allow think as country so think.',
    ],
  },
  {
    title: 'Innovative exuding knowledge user',
    authors: ['Deborah Watson', 'Jack Church'],
    ISBN: '978-0-1706733911-58986-9',
    publishers: ['Bailey-Bowman', 'Sanchez-Curtis'],
    quantityAvailable: 47,
    price: 736127,
    summary:
      'Challenge this process sort particularly drug. Candidate site night. Down mouth behavior.',
    averageRating: 3.4,
    genres: ['Memoir', 'Detective'],
    reviews: ['Study sometimes blue run either.'],
  },
  {
    title: 'Fully-configurable fault-tolerant protocol',
    authors: ['Kelly Lucas', 'Ryan Sanchez'],
    ISBN: '978-0-1706733911-11283-9',
    publishers: ['Kaufman, Brown and Evans'],
    quantityAvailable: 37,
    price: 333102,
    summary:
      'Inside very trial past available. Relationship cell walk health daughter. Manage physical ability friend yeah capital.',
    averageRating: 4.7,
    genres: ['Crime', 'Science Fiction', 'Steampunk'],
    reviews: [
      'Behavior bill interest air middle write.',
      'Phone audience protect.',
      'Away most attack support sense week.',
    ],
  },
  {
    title: 'Ergonomic non-volatile installation',
    authors: ['Lindsey Bryant', 'Julie Freeman', 'Tonya Friedman MD'],
    ISBN: '978-0-1706733911-71077-9',
    publishers: ['Collins, Warner and Frank'],
    quantityAvailable: 34,
    price: 269694,
    summary: 'Mouth better artist.',
    averageRating: 3.1,
    genres: ['Cozy Mystery', 'Techno-Thriller'],
    reviews: [
      'Wait happen produce yeah fact spring forget.',
      'Less nice car successful stage task kid at.',
    ],
  },
  {
    title: 'Compatible content-based array',
    authors: ['Jason Leblanc', 'Theresa Taylor', 'Patricia Barnes'],
    ISBN: '978-0-1706733911-43472-9',
    publishers: ['Nguyen Ltd'],
    quantityAvailable: 48,
    price: 928583,
    summary: 'Action born bill full. The eye somebody side series.',
    averageRating: 3.2,
    genres: ['Hardboiled Mystery', 'Post-Apocalyptic', 'Historical Mystery'],
    reviews: [
      'Year paper increase of.',
      'Civil hope beautiful scene lay.',
      'Plant child often manage sell heart international.',
    ],
  },
  {
    title: 'Up-sized encompassing interface',
    authors: ['Clifford Farrell'],
    ISBN: '978-0-1706733911-25006-9',
    publishers: ['Green, Smith and Braun'],
    quantityAvailable: 50,
    price: 667419,
    summary:
      'Dog difference dream during federal question. Ahead between itself beat. Than other get series like each.',
    averageRating: 4.4,
    genres: ['Mystery Thriller', 'Supernatural Horror', 'Autobiography'],
    reviews: ['Whole American can way value must response.'],
  },
  {
    title: 'Customizable eco-centric knowledgebase',
    authors: ['Spencer Griffin'],
    ISBN: '978-0-1706733911-40528-9',
    publishers: ['Marquez-Vazquez'],
    quantityAvailable: 50,
    price: 592911,
    summary:
      'Effect position color to. Name house either their structure role half. Pretty at agent actually report collection enough. Small section between than line.',
    averageRating: 5.0,
    genres: ['Crime', 'Alternate History', 'Psychological Thriller'],
    reviews: ['Air everybody high want.'],
  },
  {
    title: 'Down-sized real-time website',
    authors: ['Ashley Kelly', 'Adam Vasquez'],
    ISBN: '978-0-1706733911-11829-9',
    publishers: ['Gaines and Sons'],
    quantityAvailable: 5,
    price: 860957,
    summary:
      'Leg great second continue size myself executive. Mission past movie could family. Author blue option hundred glass structure.',
    averageRating: 4.8,
    genres: ['Action', 'Historical Horror'],
    reviews: [
      'Remain center pull prevent floor.',
      'Positive center truth other.',
    ],
  },
  {
    title: 'Fundamental reciprocal conglomeration',
    authors: ['Elizabeth Garcia'],
    ISBN: '978-0-1706733911-81281-9',
    publishers: ['Santos, Johnson and Thomas', 'Tyler Group'],
    quantityAvailable: 14,
    price: 181259,
    summary: 'Item than resource. Save director something.',
    averageRating: 3.5,
    genres: ['Fiction', 'Romance'],
    reviews: [
      'Character executive great imagine election.',
      'Whom police agreement avoid process.',
      'Include bank my drug adult central these.',
    ],
  },
  {
    title: 'Progressive real-time product',
    authors: ['Jose Robinson', 'Jason Rios'],
    ISBN: '978-0-1706733911-49342-9',
    publishers: ['Harvey, Skinner and Gomez'],
    quantityAvailable: 18,
    price: 395005,
    summary:
      'Song heavy most recognize partner both paper. Since be how attention respond. Ever window while how.',
    averageRating: 3.1,
    genres: ['Space Opera', 'Historical Fantasy'],
    reviews: ['Hit sense these heavy.', 'Candidate degree meeting.'],
  },
  {
    title: 'Switchable heuristic model',
    authors: ['Jose Lee'],
    ISBN: '978-0-1706733911-57638-9',
    publishers: ['James-Ramsey', 'Figueroa-Robinson'],
    quantityAvailable: 44,
    price: 508006,
    summary:
      'Song direction total happen firm. Trip five control. Expect major candidate partner. Hot a meet concern such result.',
    averageRating: 3.1,
    genres: ['Epic Fantasy', 'Cozy Mystery'],
    reviews: [
      'Follow first still seek.',
      'Kind national establish girl.',
      'Southern risk usually have Democrat throw rather.',
    ],
  },
  {
    title: 'Quality-focused tertiary hardware',
    authors: ['Nicole Smith', 'Terry Day'],
    ISBN: '978-0-1706733911-87175-9',
    publishers: ['Salinas, Cox and Hudson', 'Gonzalez LLC'],
    quantityAvailable: 34,
    price: 803636,
    summary:
      'Seat development difficult Mrs page me back. Wish always ago street generation.',
    averageRating: 4.0,
    genres: ['Lovecraftian Horror', 'Military'],
    reviews: [
      'Play event little already whole around.',
      'Sure easy gas back hit use do.',
      'Leg along challenge certainly key realize.',
    ],
  },
  {
    title: 'Profound radical open system',
    authors: ['Morgan Rich', 'Wanda Spencer', 'Emily James'],
    ISBN: '978-0-1706733911-20565-9',
    publishers: ['Bell-English', 'Mitchell Ltd'],
    quantityAvailable: 21,
    price: 348640,
    summary:
      'Sometimes growth industry concern detail. Coach everyone take back capital many. Message civil actually help call also least win.',
    averageRating: 4.3,
    genres: ['Historical Horror'],
    reviews: [
      'Leader board field teach better role animal.',
      'Mention for force.',
      'Few statement fact.',
    ],
  },
  {
    title: 'Public-key exuding challenge',
    authors: ['Michael Hood', 'Catherine Mitchell', 'Isaac Williams'],
    ISBN: '978-0-1706733911-81494-9',
    publishers: ['Estrada-Wilson'],
    quantityAvailable: 9,
    price: 631028,
    summary:
      'Magazine seem marriage stand. Possible daughter age now east region church.',
    averageRating: 4.0,
    genres: ['Gothic', 'Psychological Horror'],
    reviews: ['Wide until tonight particularly majority risk skill.'],
  },
  {
    title: 'Balanced 24/7 definition',
    authors: ['Erin Jackson', 'Amanda Johnson', 'Benjamin Young'],
    ISBN: '978-0-1706733911-40104-9',
    publishers: ['Taylor, Booker and Sims'],
    quantityAvailable: 49,
    price: 23790,
    summary:
      'Agreement they manage difficult main water yeah. Foreign population life must hold window.',
    averageRating: 3.5,
    genres: ['Horror', 'Paranormal Fantasy', 'Paranormal Romance'],
    reviews: ['Class in long industry authority year something.'],
  },
  {
    title: 'Open-source solution-oriented toolset',
    authors: ['Susan Butler'],
    ISBN: '978-0-1706733911-33754-9',
    publishers: ['Ortega, Smith and Powell', 'Young-Manning'],
    quantityAvailable: 41,
    price: 560538,
    summary:
      'Natural discussion structure not. Push fish behavior design something hair that.',
    averageRating: 4.0,
    genres: ['Steampunk'],
    reviews: [
      'Other clearly success treat according play investment.',
      'Nature front just high even how would general.',
      'Teacher this look.',
    ],
  },
  {
    title: 'Profit-focused needs-based process improvement',
    authors: ['Christopher Smith DDS'],
    ISBN: '978-0-1706733911-19048-9',
    publishers: ['Schultz and Sons', 'Rivera, Johnson and Montgomery'],
    quantityAvailable: 16,
    price: 813995,
    summary:
      'Challenge often vote home data lose catch with. Away south throughout owner big across true evidence. Kitchen let final situation reflect.',
    averageRating: 3.2,
    genres: ['Fantasy', 'Paranormal Fantasy'],
    reviews: [
      'Anyone hair likely east fall fill.',
      'Understand everybody protect.',
      'Executive away cell performance charge human.',
    ],
  },
  {
    title: 'De-engineered intermediate function',
    authors: ['George Case', 'Henry Dawson', 'Matthew Boyd'],
    ISBN: '978-0-1706733911-59197-9',
    publishers: ['Flores Ltd', 'Sandoval, Yates and Shelton'],
    quantityAvailable: 13,
    price: 146508,
    summary:
      'Sort month suddenly require. Police population cell item what style way. Hot fire yeah hair yard.',
    averageRating: 4.9,
    genres: ['Political Thriller', 'Gothic Horror', 'Space Opera'],
    reviews: ['Effort even chance actually.', 'Name do point.'],
  },
  {
    title: 'Customizable holistic circuit',
    authors: ['Isaac Smith', 'David Dalton'],
    ISBN: '978-0-1706733911-36552-9',
    publishers: ['Gibson Group', 'Kelly, Meza and Glover'],
    quantityAvailable: 21,
    price: 790551,
    summary:
      'Color political listen conference high population involve. Low authority economy health do forward half health.',
    averageRating: 4.2,
    genres: ['High Fantasy', 'Military', 'Travel'],
    reviews: ['Even improve sense loss.'],
  },
  {
    title: 'Quality-focused reciprocal orchestration',
    authors: ['Lori Thompson', 'Manuel Johnson'],
    ISBN: '978-0-1706733911-23915-9',
    publishers: ['Benson Inc'],
    quantityAvailable: 36,
    price: 290369,
    summary:
      'Discussion why party along believe western. Surface enjoy director different focus. Nice drug team would speak.',
    averageRating: 3.1,
    genres: ['Urban Fantasy'],
    reviews: ['Indeed seven authority group.', 'Keep well wait.'],
  },
  {
    title: 'Open-source asynchronous solution',
    authors: ['Christopher Thompson'],
    ISBN: '978-0-1706733911-78104-9',
    publishers: ['Williams-Adams', 'Fleming, Smith and Johnson'],
    quantityAvailable: 49,
    price: 895098,
    summary: 'Ball Mr light across difference tough might bar.',
    averageRating: 3.7,
    genres: ['Espionage', 'Historical Mystery', 'Soft Science Fiction'],
    reviews: [
      'Why responsibility explain through affect wall imagine develop.',
      'Still simply close life as soon answer.',
      'Always attorney ability my.',
    ],
  },
  {
    title: 'Expanded clear-thinking array',
    authors: ['Michelle Greene', 'Denise Turner'],
    ISBN: '978-0-1706733911-61079-9',
    publishers: ['Williams PLC'],
    quantityAvailable: 14,
    price: 748397,
    summary:
      'Determine design leader area without glass. Development figure policy piece hand recently behind research. Energy back glass sit news election. Leader him city.',
    averageRating: 4.0,
    genres: ['Science Fiction', 'Alternate History'],
    reviews: ['Effort clearly anyone total future.'],
  },
  {
    title: 'Optional non-volatile parallelism',
    authors: ['Derek Clark'],
    ISBN: '978-0-1706733911-57182-9',
    publishers: ['Ramsey, Greene and Thompson', 'Montgomery-Crane'],
    quantityAvailable: 17,
    price: 79987,
    summary:
      'Rate little firm size. Smile tax population security service same boy. Family tax public successful.',
    averageRating: 3.4,
    genres: ['Hardboiled Mystery'],
    reviews: ['Argue successful son of.', 'Line would meet or enter.'],
  },
  {
    title: 'Implemented needs-based success',
    authors: ['William Brooks', 'Kenneth Dunn', 'Ronald James'],
    ISBN: '978-0-1706733911-60040-9',
    publishers: ['Gibson Ltd'],
    quantityAvailable: 10,
    price: 921477,
    summary:
      'Without receive my figure course week. Provide laugh perhaps. Record consider still.',
    averageRating: 3.8,
    genres: ['Horror'],
    reviews: [
      'Research peace side five PM.',
      'Because charge instead race break ten.',
      'Information try next good officer.',
    ],
  },
  {
    title: 'Innovative tertiary array',
    authors: ['Gary Roberson', 'Lisa Long', 'Melissa Miller MD'],
    ISBN: '978-0-1706733911-79045-9',
    publishers: ['Cox, White and Thomas', 'Williams, Robbins and Nguyen'],
    quantityAvailable: 38,
    price: 130827,
    summary:
      'Foot of drug home attack increase turn score. Rise suffer collection red five we near.',
    averageRating: 3.4,
    genres: ['Low Fantasy', 'Psychological Horror'],
    reviews: [
      'Recognize customer walk build.',
      'Them college purpose long result raise coach.',
      'White medical next shake.',
    ],
  },
  {
    title: 'Cross-group cohesive capability',
    authors: ['Juan Galloway', 'Patricia Brown', 'Madeline Green'],
    ISBN: '978-0-1706733911-99219-9',
    publishers: ['Sullivan-Mullins'],
    quantityAvailable: 10,
    price: 168907,
    summary:
      'Participant pretty job degree information as. Response out example vote. Research red career compare bill the month.',
    averageRating: 4.6,
    genres: ['Psychological Thriller', 'Alternate History'],
    reviews: ['Trip apply I member.'],
  },
  {
    title: 'Function-based 3rdgeneration Graphic Interface',
    authors: ['Heather Singh', 'Betty Williams', 'Robert Johnson'],
    ISBN: '978-0-1706733911-58289-9',
    publishers: ['Hinton-Lewis', 'Castaneda PLC'],
    quantityAvailable: 31,
    price: 67290,
    summary:
      'Draw way girl pass arrive analysis politics admit. Everybody as add similar performance alone develop stop.',
    averageRating: 4.3,
    genres: ['Espionage', 'Psychological Horror'],
    reviews: [
      'By but summer decide factor case notice name.',
      'Second camera model nature drive air war.',
    ],
  },
  {
    title: 'Polarized full-range portal',
    authors: ['Sandra Estrada', 'Anna Baker', 'Andrea Cooper'],
    ISBN: '978-0-1706733911-18693-9',
    publishers: ['Hernandez-Martin', 'Chavez, Kerr and Thomas'],
    quantityAvailable: 34,
    price: 785209,
    summary: 'Garden page eye wonder including music by nature.',
    averageRating: 4.5,
    genres: ['Thriller', 'Adventure Romance', 'Mystery Thriller'],
    reviews: ['Option central law food would audience.'],
  },
  {
    title: 'Robust dynamic structure',
    authors: ['Catherine Smith', 'David Perez', 'Keith Johnson'],
    ISBN: '978-0-1706733912-88602-9',
    publishers: ['Jordan PLC'],
    quantityAvailable: 5,
    price: 274852,
    summary:
      'Water clear across organization hope term center. Agent box build moment stock can. Real produce say drive win none suddenly.',
    averageRating: 4.9,
    genres: ['Espionage'],
    reviews: [
      'Clear respond argue police sign great billion.',
      'Responsibility drive peace full marriage process little bank.',
      'Party interview us they development door.',
    ],
  },
  {
    title: 'Triple-buffered global intranet',
    authors: ['Theresa Allen'],
    ISBN: '978-0-1706733912-97679-9',
    publishers: ['Hahn, Smith and Sullivan', 'Valdez, Clark and Sanchez'],
    quantityAvailable: 6,
    price: 479465,
    summary:
      'Against quickly draw according eye above reveal research. Than kitchen property seat next. Blue film time road design.',
    averageRating: 4.0,
    genres: ['Historical Horror', 'Science Fiction'],
    reviews: [
      'Interview attention popular meeting onto time usually majority.',
      'But environmental professor.',
      'Themselves two blue their claim service.',
    ],
  },
  {
    title: 'Realigned fresh-thinking benchmark',
    authors: ['Kaitlyn Brown', 'Mrs. Vicki Anderson MD'],
    ISBN: '978-0-1706733912-81104-9',
    publishers: ['Barron-Kelly'],
    quantityAvailable: 29,
    price: 964052,
    summary:
      'Help usually both manage prove. Subject trial six strategy. Successful edge reveal that stay.',
    averageRating: 3.7,
    genres: ['Supernatural', 'Autobiography', 'Biography'],
    reviews: [
      'Join suggest growth source late figure list.',
      'End fight main.',
      'Defense red argue nor specific put.',
    ],
  },
  {
    title: 'Managed uniform capability',
    authors: ['Christopher Ross', 'Michael Miller', 'Steve Gibson'],
    ISBN: '978-0-1706733912-71777-9',
    publishers: ['Hamilton-Richardson', 'Figueroa-Allen'],
    quantityAvailable: 20,
    price: 335908,
    summary:
      'Agency stock together why. Material continue bag drug job small film. Water really why similar pressure.',
    averageRating: 3.8,
    genres: ['Science Fiction', 'Cyberpunk'],
    reviews: [
      'Sister along last accept response.',
      'Price tough break class rise.',
      'Quickly capital yard skill talk occur.',
    ],
  },
  {
    title: 'Up-sized even-keeled website',
    authors: ['Keith Williams'],
    ISBN: '978-0-1706733912-63780-9',
    publishers: ['Estrada Group'],
    quantityAvailable: 18,
    price: 705830,
    summary:
      'Hard hour indicate effort growth. Ball position sign meeting day available meet.',
    averageRating: 4.9,
    genres: ['Paranormal', 'Psychological Thriller'],
    reviews: [
      'Middle research approach free.',
      'Owner century respond perform.',
    ],
  },
  {
    title: 'Mandatory homogeneous info-mediaries',
    authors: ['Veronica Bruce'],
    ISBN: '978-0-1706733912-36142-9',
    publishers: ['Moore, Barry and Martinez', 'Roberts-May'],
    quantityAvailable: 45,
    price: 628092,
    summary:
      'Movement simple general management only again. Travel democratic ever debate.',
    averageRating: 3.8,
    genres: ['Lovecraftian Horror', 'Autobiography', 'Soft Science Fiction'],
    reviews: [
      'Us check pressure.',
      'Face impact certain ahead experience save nearly budget.',
      'Too prepare notice want.',
    ],
  },
  {
    title: 'Seamless explicit neural-net',
    authors: ['Latoya Lee'],
    ISBN: '978-0-1706733912-39468-9',
    publishers: ['Kirk Ltd', 'Briggs PLC'],
    quantityAvailable: 50,
    price: 438796,
    summary: 'Father stay year within speech election financial.',
    averageRating: 3.2,
    genres: ['Drama', 'Political Thriller'],
    reviews: ['Affect grow song not central.'],
  },
  {
    title: 'Multi-channeled human-resource moratorium',
    authors: ['Emily Foster', 'Cathy Lin', 'Lisa Sanders'],
    ISBN: '978-0-1706733912-18548-9',
    publishers: ['Ingram, Hale and Cross'],
    quantityAvailable: 7,
    price: 988335,
    summary:
      'Read use employee record. Use new money officer between today well. Them class ask about mouth.',
    averageRating: 4.6,
    genres: ['Space Opera', 'Mystery Thriller', 'Travel'],
    reviews: ['College rather vote.', 'Manage half which from.'],
  },
  {
    title: 'Fully-configurable grid-enabled ability',
    authors: ['Christy Guzman', 'Jason Christian', 'Edwin Austin'],
    ISBN: '978-0-1706733912-16617-9',
    publishers: ['Howell-Ortega'],
    quantityAvailable: 42,
    price: 525208,
    summary:
      'Look reduce risk human page middle. Change long call issue small wonder analysis.',
    averageRating: 3.5,
    genres: ['Hard Science Fiction', 'Historical Horror', 'Horror'],
    reviews: ['Loss seem series power kind.'],
  },
  {
    title: 'Innovative value-added utilization',
    authors: ['Joel Harvey', 'Melissa White', 'Hunter Williams'],
    ISBN: '978-0-1706733912-75965-9',
    publishers: ['Hensley Inc', 'Mitchell Ltd'],
    quantityAvailable: 7,
    price: 379217,
    summary:
      'Week security loss he inside worker. Late difficult too subject mention.',
    averageRating: 4.8,
    genres: ['Science Fiction', 'Horror'],
    reviews: ['Meet herself represent term method population.'],
  },
  {
    title: 'Cloned systemic orchestration',
    authors: ['Curtis Fuller', 'Aimee Malone', 'Michael Sanchez'],
    ISBN: '978-0-1706733912-46839-9',
    publishers: ['Hess-Pham'],
    quantityAvailable: 22,
    price: 25174,
    summary: 'American middle fear.',
    averageRating: 3.3,
    genres: ['Hardboiled Mystery'],
    reviews: [
      'Somebody natural its customer prepare plan.',
      'Tell most ten scene.',
      'Reflect our admit poor most chair source.',
    ],
  },
  {
    title: 'Multi-lateral secondary solution',
    authors: ['Emma Alvarado', 'Kimberly Carroll'],
    ISBN: '978-0-1706733912-99431-9',
    publishers: ['Cantrell-Wells', 'Fernandez and Sons'],
    quantityAvailable: 37,
    price: 478407,
    summary: 'Any daughter ready relate pick property control professor.',
    averageRating: 3.0,
    genres: ['Horror', 'Espionage'],
    reviews: [
      'Blood book shoulder yeah would.',
      'Guy leg charge create cell south unit.',
      'Situation piece record.',
    ],
  },
  {
    title: 'Cloned context-sensitive definition',
    authors: ['Peter Rogers'],
    ISBN: '978-0-1706733912-20164-9',
    publishers: ['Hamilton Group'],
    quantityAvailable: 36,
    price: 976889,
    summary:
      'Probably ready half home into attention. Floor news minute positive air tough property feeling. Major herself light statement.',
    averageRating: 4.3,
    genres: ['Paranormal', 'Non-Fiction'],
    reviews: ['Gun boy teach artist at deal responsibility.'],
  },
  {
    title: 'Universal encompassing flexibility',
    authors: ['Kari Frye', 'Destiny Wright', 'Gregory Price'],
    ISBN: '978-0-1706733912-13917-9',
    publishers: ['Ward-Woods'],
    quantityAvailable: 36,
    price: 504686,
    summary:
      'Because player local offer choice Congress son work. Test rise consider general movie recent. Choice Congress fight office. Nice mention billion model growth key high.',
    averageRating: 5.0,
    genres: ['Satire'],
    reviews: [
      'Through democratic manage office adult arrive.',
      'This thing drive risk hour just.',
    ],
  },
  {
    title: 'Ameliorated demand-driven complexity',
    authors: ['Kimberly Love', 'Jennifer Neal'],
    ISBN: '978-0-1706733912-76375-9',
    publishers: ['Santiago-Kelly'],
    quantityAvailable: 49,
    price: 854931,
    summary:
      'Billion to result fast far wrong. Yourself sport system stage evidence summer police catch. Place happy sea bill.',
    averageRating: 3.1,
    genres: ['Detective'],
    reviews: [
      'Performance none drive option.',
      'Military police skin today reach edge as.',
    ],
  },
  {
    title: 'Customizable disintermediate firmware',
    authors: ['Shane Hunter', 'Christopher Smith', 'Carolyn Barker'],
    ISBN: '978-0-1706733912-51126-9',
    publishers: ['Miller, Robinson and Baldwin'],
    quantityAvailable: 5,
    price: 453296,
    summary:
      'Air choose letter financial carry rather exactly. Life measure save raise.',
    averageRating: 3.7,
    genres: ['Fantasy', 'Comedy', 'Adventure'],
    reviews: ['Table cup specific call leader.', 'Activity radio including.'],
  },
  {
    title: 'Customizable multimedia flexibility',
    authors: ['Daniel Williams'],
    ISBN: '978-0-1706733912-54515-9',
    publishers: ['Perez-Huang'],
    quantityAvailable: 25,
    price: 171533,
    summary:
      'Me imagine actually industry. Herself smile establish enter management realize.',
    averageRating: 3.5,
    genres: ['Non-Fiction'],
    reviews: ['Learn week better sister daughter.'],
  },
  {
    title: 'Intuitive value-added focus group',
    authors: ['Frank Valentine', 'Mark Ortega'],
    ISBN: '978-0-1706733912-92813-9',
    publishers: ['Keith-Holden', 'Bishop-Velasquez'],
    quantityAvailable: 38,
    price: 846571,
    summary:
      'Relate democratic whether call. Rock increase later born general. Military war police rate sport so learn. Fear during here test.',
    averageRating: 3.1,
    genres: ['Space Opera', 'Dark Fantasy', 'Cyberpunk'],
    reviews: ['Country particular beautiful decide name.'],
  },
  {
    title: 'Synergized holistic help-desk',
    authors: ['Cindy Wiggins'],
    ISBN: '978-0-1706733912-80340-9',
    publishers: ['Rodriguez-Snyder', 'West-Roberts'],
    quantityAvailable: 14,
    price: 303880,
    summary:
      'Something little garden individual. Wind quality memory rate shake my beautiful. Why explain sit western into.',
    averageRating: 4.2,
    genres: ['Low Fantasy', 'Urban Fantasy'],
    reviews: [
      'Commercial would any thousand mind.',
      'Structure wrong risk suddenly main.',
      'Young meeting interview job.',
    ],
  },
  {
    title: 'Business-focused composite implementation',
    authors: ['Yesenia Smith'],
    ISBN: '978-0-1706733912-67807-9',
    publishers: ['Day, Russell and Rogers'],
    quantityAvailable: 8,
    price: 209991,
    summary:
      'Small marriage go loss see affect defense. Certainly because about trade side laugh.',
    averageRating: 4.0,
    genres: ['Science Fiction', 'Non-Fiction', 'Science Fiction'],
    reviews: [
      'Later form establish bad upon.',
      'Ahead start again.',
      'Rich check major employee.',
    ],
  },
  {
    title: 'Organized user-facing protocol',
    authors: ['Traci Moran', 'Carol Chang', 'Jonathan Lyons'],
    ISBN: '978-0-1706733912-82372-9',
    publishers: ['Wilson Inc'],
    quantityAvailable: 8,
    price: 739439,
    summary:
      'Treat field account along course sister father. Rest free response town.',
    averageRating: 4.3,
    genres: ['Urban Fantasy', 'Sword and Sorcery'],
    reviews: ['Music west all drug evidence gas fly.'],
  },
  {
    title: 'Versatile even-keeled infrastructure',
    authors: ['Jessica Cox', 'Paul Johnson'],
    ISBN: '978-0-1706733912-92983-9',
    publishers: ['Thomas, Smith and Mccann'],
    quantityAvailable: 6,
    price: 626287,
    summary:
      'Quite may sign visit time. Of heart ever finally official difference a.',
    averageRating: 4.8,
    genres: ['Cyberpunk'],
    reviews: ['Maybe keep word.'],
  },
  {
    title: 'Universal dynamic infrastructure',
    authors: ['Angela Campos', 'John Li'],
    ISBN: '978-0-1706733912-25131-9',
    publishers: ['Peterson, Young and Benson'],
    quantityAvailable: 17,
    price: 417879,
    summary:
      'Baby federal baby remain art opportunity group where. Rule skill tree who chair.',
    averageRating: 3.9,
    genres: ['Detective'],
    reviews: ['Energy senior sometimes.'],
  },
  {
    title: 'Realigned radical strategy',
    authors: ['Matthew Bryan', 'Diane Long'],
    ISBN: '978-0-1706733912-55751-9',
    publishers: ['Williams-Pearson', 'Wells, Ruiz and Chavez'],
    quantityAvailable: 43,
    price: 398805,
    summary:
      'Know task standard green across tax. Rock summer hot really try key present.',
    averageRating: 4.8,
    genres: ['Autobiography'],
    reviews: ['Next activity free soon friend ball.'],
  },
  {
    title: 'Upgradable multi-tasking extranet',
    authors: ['Olivia Cook'],
    ISBN: '978-0-1706733912-61875-9',
    publishers: ['Morrison, Carroll and Orr', 'Pittman, Smith and Jones'],
    quantityAvailable: 44,
    price: 750719,
    summary:
      'Relationship weight whole man table message. National paper bag right month agree stock.',
    averageRating: 3.4,
    genres: ['Science Fiction', 'Non-Fiction'],
    reviews: [
      'Include condition news firm sound remain become.',
      'My west left we her science.',
      'Hundred actually prevent yes indeed mean sell.',
    ],
  },
  {
    title: 'Persevering dynamic throughput',
    authors: ['Jermaine White'],
    ISBN: '978-0-1706733912-62263-9',
    publishers: ['Smith, Johnson and Cook'],
    quantityAvailable: 19,
    price: 361360,
    summary:
      'Option explain green however ahead some. Give guess not reduce including. Training finally quite sort. Allow fear decide candidate world toward.',
    averageRating: 3.6,
    genres: ['Science Fiction', 'Detective', 'Adventure'],
    reviews: [
      'Win either soon bring southern.',
      'Ball start partner.',
      'Let against professor hospital upon wind.',
    ],
  },
  {
    title: 'Intuitive cohesive contingency',
    authors: ['Faith Wells', 'Jessica Smith'],
    ISBN: '978-0-1706733912-82638-9',
    publishers: ['Blair, Patton and Thomas', 'Martin, Berg and Ellison'],
    quantityAvailable: 10,
    price: 415646,
    summary:
      'Seek college such interview fact benefit. Soldier fight pay animal present. Night television investment assume pattern.',
    averageRating: 4.1,
    genres: ['Mystery Thriller', "Women's Fiction", 'Alternate History'],
    reviews: [
      'Store none nation culture find Mr.',
      'Pattern few other protect step seat them quickly.',
    ],
  },
  {
    title: 'Open-architected responsive migration',
    authors: ['Joel Durham', 'Mike Floyd', 'Allison Cox'],
    ISBN: '978-0-1706733912-93548-9',
    publishers: ['Lewis Ltd'],
    quantityAvailable: 31,
    price: 401806,
    summary: 'Wait could necessary article these free other.',
    averageRating: 4.8,
    genres: ['Military', 'Historical Fiction', 'Adventure'],
    reviews: ['Whether physical on fly.'],
  },
  {
    title: 'Versatile needs-based approach',
    authors: ['Richard Castillo'],
    ISBN: '978-0-1706733912-21588-9',
    publishers: ['Russo, Alexander and Chen', 'Miranda, King and Le'],
    quantityAvailable: 5,
    price: 331463,
    summary:
      'Compare them seem system maintain each. Economic improve good structure.',
    averageRating: 3.3,
    genres: ['Cyberpunk', 'Historical Fiction'],
    reviews: [
      'Minute just position Congress standard place single wall.',
      'Skill whatever lawyer speech none parent as.',
      'Deal heart may effect task whatever.',
    ],
  },
  {
    title: 'Synchronized fault-tolerant policy',
    authors: ['Samuel Lucas', 'Bianca Collins', 'Amber Combs'],
    ISBN: '978-0-1706733912-36505-9',
    publishers: ['Kane-Miller'],
    quantityAvailable: 44,
    price: 581926,
    summary: 'Skin seven others movie not.',
    averageRating: 3.1,
    genres: ['Historical Fiction', 'Military', 'Historical Horror'],
    reviews: [
      'Official so last senior must heavy.',
      'Can room page trip situation.',
    ],
  },
  {
    title: 'Innovative reciprocal policy',
    authors: ['Timothy Garcia', 'Jennifer Nolan', 'Gregory Mathis'],
    ISBN: '978-0-1706733912-79016-9',
    publishers: ['Jones, Roberts and Love'],
    quantityAvailable: 26,
    price: 518248,
    summary:
      'Mouth form however worker bag push decision. Enough poor important think how choice.',
    averageRating: 4.7,
    genres: ['Drama'],
    reviews: [
      'Maybe executive low certain after necessary professor.',
      'Find travel sport everything dog.',
    ],
  },
  {
    title: 'Reactive exuding matrices',
    authors: ['Alex Austin', 'Marvin Lambert', 'Taylor Walker DVM'],
    ISBN: '978-0-1706733912-57872-9',
    publishers: ['Johnson Group'],
    quantityAvailable: 39,
    price: 297064,
    summary:
      'Travel finish oil travel when might try. American write condition decision. Really attack go involve.',
    averageRating: 3.5,
    genres: ['Political Thriller'],
    reviews: [
      'Relate wrong large set customer according information myself.',
      'Evening else blood smile national common world son.',
    ],
  },
  {
    title: 'Future-proofed optimizing benchmark',
    authors: ['Michael Martinez', 'Christopher Pugh'],
    ISBN: '978-0-1706733912-42906-9',
    publishers: ['Mckay, Brown and Campbell', 'Graham-Davidson'],
    quantityAvailable: 49,
    price: 395074,
    summary:
      'News everything term Mrs enjoy. Class sound TV call rise address. Black notice career national yet measure. Involve rather everyone better rather however art.',
    averageRating: 3.4,
    genres: ['Thriller'],
    reviews: ['Fine for deal her live size.', 'Consumer public young court.'],
  },
  {
    title: 'De-engineered global contingency',
    authors: ['Kelly Jones', 'Lauren Coleman', 'Maria Berger'],
    ISBN: '978-0-1706733912-23173-9',
    publishers: ['Henderson PLC', 'Bryant, Bates and Sullivan'],
    quantityAvailable: 44,
    price: 782277,
    summary: 'Attention moment key. Real include be pay score record to.',
    averageRating: 4.3,
    genres: ['Historical Romance'],
    reviews: [
      'Capital minute election course pattern baby.',
      'Admit amount institution.',
      'Beyond eight center rise born use.',
    ],
  },
  {
    title: 'Polarized maximized time-frame',
    authors: ['Vincent Marsh', 'Cynthia Swanson', 'Travis Kline'],
    ISBN: '978-0-1706733912-34855-9',
    publishers: ['Calderon, Hart and Morris', 'Williams, Abbott and Nelson'],
    quantityAvailable: 16,
    price: 484663,
    summary: 'Carry hundred weight concern. Peace out assume local idea box.',
    averageRating: 4.9,
    genres: ['Business', 'Espionage'],
    reviews: [
      'Improve detail natural player house social.',
      'Company street none without dog.',
    ],
  },
  {
    title: 'Multi-tiered client-driven Internet solution',
    authors: ['Mr. Jason Marshall DVM', 'Ricardo Sharp'],
    ISBN: '978-0-1706733912-67941-9',
    publishers: ['Braun-Hill'],
    quantityAvailable: 27,
    price: 703186,
    summary: 'Everybody catch second rock wide. End side man through agree.',
    averageRating: 4.8,
    genres: ['Espionage'],
    reviews: [
      'Ready among choice late floor reason under.',
      'Laugh Mr trade whether visit hot.',
      'Nearly yet down color east reach.',
    ],
  },
  {
    title: 'Networked encompassing conglomeration',
    authors: ['Anna Strong', 'Oscar Berry', 'Jonathan Reeves'],
    ISBN: '978-0-1706733912-53438-9',
    publishers: ['Daniel, Eaton and Perkins'],
    quantityAvailable: 39,
    price: 502088,
    summary:
      'This cultural especially hand eat. Work couple late join gas. Choice radio trial fish trouble whatever cost not. Her or adult than.',
    averageRating: 4.6,
    genres: ['Historical Fiction', 'Historical Romance'],
    reviews: [
      'Figure door without act job next another.',
      'Cause view popular public good people.',
    ],
  },
  {
    title: 'Reverse-engineered context-sensitive emulation',
    authors: ['Ryan Olson', 'Eric Harding', 'Melissa Vazquez'],
    ISBN: '978-0-1706733912-55276-9',
    publishers: ['Armstrong LLC', 'Taylor, Brady and Sanchez'],
    quantityAvailable: 16,
    price: 502497,
    summary:
      'Ability citizen art. Describe address guess reach into method. Future sort see.',
    averageRating: 3.6,
    genres: ['Action'],
    reviews: [
      'Reality charge admit ground.',
      'Four seat take firm quickly role room.',
    ],
  },
  {
    title: 'Organized actuating Graphic Interface',
    authors: ['Adrienne Wise', 'Nicole Little', 'Javier Smith'],
    ISBN: '978-0-1706733912-72915-9',
    publishers: ['Barker-Mckinney', 'Ross and Sons'],
    quantityAvailable: 16,
    price: 910222,
    summary: 'But capital increase. Everyone condition military.',
    averageRating: 4.8,
    genres: ['Political Thriller'],
    reviews: [
      'New laugh weight once material.',
      'Community machine determine travel age drug.',
      'Administration agent employee medical.',
    ],
  },
  {
    title: 'Upgradable context-sensitive paradigm',
    authors: ['Allen Hill', 'Todd Martin'],
    ISBN: '978-0-1706733912-44074-9',
    publishers: ['James Group', 'Rice-Rice'],
    quantityAvailable: 24,
    price: 758339,
    summary:
      'Animal win probably. Suffer east similar consumer mind its international.',
    averageRating: 4.1,
    genres: ['Historical Fantasy', 'Steampunk', "Women's Fiction"],
    reviews: [
      'Hold north able size officer outside bed particularly.',
      'Every training forget expect ability.',
    ],
  },
  {
    title: 'Quality-focused transitional pricing structure',
    authors: ['Gary Evans'],
    ISBN: '978-0-1706733912-43607-9',
    publishers: ['Yang Group', 'Hull LLC'],
    quantityAvailable: 10,
    price: 768251,
    summary:
      'Thus talk wonder. Discussion thought few budget result official professional plant. Something participant study let beat summer.',
    averageRating: 3.8,
    genres: ['Epic Fantasy', 'Time Travel Romance', 'Historical Fantasy'],
    reviews: [
      'Yes final Democrat sell fish.',
      'Individual table different high.',
      'Course talk trip someone lead win.',
    ],
  },
  {
    title: 'Extended interactive paradigm',
    authors: ['Justin Norman', 'Lauren Kim', 'Thomas Jones'],
    ISBN: '978-0-1706733912-45586-9',
    publishers: ['Rogers, Kim and Baker'],
    quantityAvailable: 31,
    price: 504866,
    summary:
      'Best down one fire site. Raise dog soon left walk of. Citizen economic probably say task.',
    averageRating: 4.6,
    genres: ['Political Thriller', 'Dystopian', 'Soft Science Fiction'],
    reviews: ['South cup air next development project.'],
  },
  {
    title: 'Pre-emptive mobile interface',
    authors: ['Marisa Frazier'],
    ISBN: '978-0-1706733912-56412-9',
    publishers: ['Gonzalez-Morris', 'Frye, Hahn and Moses'],
    quantityAvailable: 32,
    price: 107253,
    summary:
      'Medical firm cup care nice friend. Dog really day establish matter prevent learn.',
    averageRating: 4.4,
    genres: ['Crime'],
    reviews: [
      'Seem hope decade policy worry huge case.',
      'Type add military pick.',
      'Season month staff perform decade.',
    ],
  },
  {
    title: 'Down-sized static frame',
    authors: ['Daniel Hartman', 'Mario Khan', 'Belinda Snyder'],
    ISBN: '978-0-1706733912-11161-9',
    publishers: ['Page Ltd'],
    quantityAvailable: 28,
    price: 546404,
    summary:
      'Join the party section. Successful talk pass must state write artist.',
    averageRating: 5.0,
    genres: ['Historical Fiction', 'Philosophy', 'Historical Mystery'],
    reviews: [
      'Run class two hit real scene smile.',
      'Kid son different produce race deal.',
    ],
  },
  {
    title: 'Programmable dedicated monitoring',
    authors: ['Victor Coleman', 'Timothy Perkins'],
    ISBN: '978-0-1706733912-23235-9',
    publishers: ['Baker, Howard and Padilla'],
    quantityAvailable: 48,
    price: 128862,
    summary:
      'Certain inside produce road television instead black. Base great course owner return pass the require.',
    averageRating: 4.6,
    genres: ['Crime', 'Fantasy', 'Supernatural Horror'],
    reviews: [
      'Trade charge item think seek firm.',
      'Thus whole she participant.',
      'Police can it later.',
    ],
  },
  {
    title: 'Cross-platform 3rdgeneration conglomeration',
    authors: ['Michael Johnson', 'Mrs. Tracy Fox', 'Marie Kim'],
    ISBN: '978-0-1706733912-82220-9',
    publishers: ['Morris Group'],
    quantityAvailable: 30,
    price: 364390,
    summary:
      'Against particularly out top traditional. Lawyer social if but several drop enough candidate.',
    averageRating: 3.7,
    genres: ['Space Opera', 'Espionage'],
    reviews: ['Actually hospital near Republican less speak score.'],
  },
  {
    title: 'Distributed attitude-oriented orchestration',
    authors: ['Kenneth Vega'],
    ISBN: '978-0-1706733912-13955-9',
    publishers: ['Cook, Smith and Pugh', 'Shaw, Dunn and Kennedy'],
    quantityAvailable: 28,
    price: 692206,
    summary:
      'Treatment involve example response stuff compare. Determine grow computer garden its evening personal. Although describe magazine mother. Never much south civil thing.',
    averageRating: 4.4,
    genres: ['Mystery Thriller', 'Utopian', 'Sword and Sorcery'],
    reviews: ['Purpose today fund meet performance.'],
  },
  {
    title: 'Multi-layered local Internet solution',
    authors: ['Bailey Salas', 'Mary Miller'],
    ISBN: '978-0-1706733912-43847-9',
    publishers: ['Davidson Inc'],
    quantityAvailable: 6,
    price: 568156,
    summary:
      'Camera return white fall buy lot source almost. Many likely civil sometimes about. Moment best hope tend above.',
    averageRating: 3.8,
    genres: ['Poetry'],
    reviews: [
      'Strategy successful popular cost somebody already.',
      'At factor hotel house.',
    ],
  },
  {
    title: 'Open-source 5thgeneration leverage',
    authors: ['Joel Smith', 'George Houston', 'Alicia Reeves'],
    ISBN: '978-0-1706733912-16688-9',
    publishers: ['Thomas-White', 'Gamble, Gibbs and Jones'],
    quantityAvailable: 41,
    price: 689259,
    summary:
      'System woman plan none sport care offer. Yes race despite century write development above. Girl war child husband reduce.',
    averageRating: 3.1,
    genres: ['Time Travel Romance', 'Legal Thriller'],
    reviews: [
      'Yet at everything fly against certainly before concern.',
      'Air guess word old position woman here.',
      'On upon character method.',
    ],
  },
  {
    title: 'Open-architected tertiary secured line',
    authors: ['Joshua Long', 'Joseph Norton', 'Dr. Gene Lee'],
    ISBN: '978-0-1706733912-30740-9',
    publishers: ['Pacheco Ltd'],
    quantityAvailable: 45,
    price: 914811,
    summary:
      'Receive city act oil something politics. Business study else than natural possible enjoy especially. Own several discover environment other race.',
    averageRating: 3.4,
    genres: ['Historical Horror', 'Espionage', 'Crime'],
    reviews: [
      'Nature finish long civil difficult.',
      'Best kid determine special outside.',
    ],
  },
  {
    title: 'Centralized 24/7 structure',
    authors: ['Cindy Coleman', 'Steven Ortiz'],
    ISBN: '978-0-1706733912-77711-9',
    publishers: ['Dominguez PLC'],
    quantityAvailable: 8,
    price: 244612,
    summary:
      'Decide set toward protect teacher candidate identify. Seven dinner week capital technology peace thought. Threat language decide myself a consider.',
    averageRating: 3.4,
    genres: ['Fantasy', "Women's Fiction", 'Adventure'],
    reviews: ['Us draw bad near.', 'Kid size large condition population.'],
  },
  {
    title: 'Self-enabling neutral policy',
    authors: ['Kathryn Morris', 'Thomas Schmidt', 'Matthew Brewer'],
    ISBN: '978-0-1706733912-84506-9',
    publishers: ['Clarke PLC', 'Ramirez PLC'],
    quantityAvailable: 17,
    price: 770871,
    summary: 'Card soldier loss ready.',
    averageRating: 3.9,
    genres: ['Science Fiction Romance', 'Fantasy'],
    reviews: ['Series always turn performance foot out and.'],
  },
  {
    title: 'Robust stable productivity',
    authors: ['Sarah Williams', 'John Campbell'],
    ISBN: '978-0-1706733912-54931-9',
    publishers: ['Burgess-Garcia', 'Hines, Garrison and Flores'],
    quantityAvailable: 32,
    price: 671340,
    summary: 'Center spend PM line. Investment role above arrive story.',
    averageRating: 3.2,
    genres: ['Self-Help', 'Dystopian'],
    reviews: [
      'Edge provide high top plan position entire drug.',
      'Would threat of cover.',
    ],
  },
  {
    title: 'Vision-oriented stable application',
    authors: ['Mrs. Kristina Stewart MD'],
    ISBN: '978-0-1706733912-79598-9',
    publishers: ['Sanchez, Hill and Rosario'],
    quantityAvailable: 32,
    price: 741802,
    summary: 'Yard history hot. Item heavy indicate mother.',
    averageRating: 4.9,
    genres: ['Romance', 'Science Fiction'],
    reviews: [
      'To message cause them number pull.',
      'Large hard although relate around hospital use moment.',
    ],
  },
  {
    title: 'Enhanced 24hour success',
    authors: ['Bradley Garner'],
    ISBN: '978-0-1706733912-52865-9',
    publishers: ['Gonzales, Berry and Williamson', 'Krueger, Casey and Bird'],
    quantityAvailable: 19,
    price: 929172,
    summary:
      'Your its field him evidence. President somebody also chance fact. Suggest whatever clearly agreement between better expert fear.',
    averageRating: 4.5,
    genres: ['Cozy Mystery'],
    reviews: [
      'Cell cell subject boy.',
      'Them thus seem short.',
      'As drop attack.',
    ],
  },
  {
    title: 'Customizable heuristic software',
    authors: ['Alexander Moran', 'Cheryl Green', 'Dr. Christopher Tyler'],
    ISBN: '978-0-1706733912-40001-9',
    publishers: ['Hughes PLC', 'Pena Inc'],
    quantityAvailable: 12,
    price: 849144,
    summary:
      'South appear cut city. Model one us base suffer authority. Carry better beautiful under on foreign itself. Chair old reduce another class heart.',
    averageRating: 4.3,
    genres: ['Science Fiction', 'Sword and Sorcery'],
    reviews: [
      'Reveal ability many voice.',
      'Raise cell total respond.',
      'None girl college significant site inside stay.',
    ],
  },
  {
    title: 'Fully-configurable cohesive implementation',
    authors: ['Tyler Gomez', 'Amber Benjamin', 'Gabrielle Horne'],
    ISBN: '978-0-1706733912-24568-9',
    publishers: ['Foster PLC', 'Harris-Robertson'],
    quantityAvailable: 28,
    price: 879925,
    summary:
      'Growth Congress positive wonder leader energy ask. Two PM spend land. Central network only end box peace.',
    averageRating: 3.6,
    genres: ['Supernatural', 'Historical Romance', 'Romantic Suspense'],
    reviews: [
      'Cause but better base pay poor.',
      'First development pressure owner one raise eye position.',
    ],
  },
  {
    title: 'Enterprise-wide 24/7 solution',
    authors: ['Jessica Murphy', 'Kristina Hill'],
    ISBN: '978-0-1706733912-68927-9',
    publishers: ['Fritz and Sons'],
    quantityAvailable: 25,
    price: 843178,
    summary:
      'Happy attack policy old return other figure. Source strong good. Should reflect item system produce protect policy.',
    averageRating: 4.2,
    genres: ['Utopian', 'Hard Science Fiction'],
    reviews: ['Discover administration concern stay political.'],
  },
  {
    title: 'Synchronized tangible synergy',
    authors: ['Dana Smith', 'Jane Holland', 'Ashley Lopez'],
    ISBN: '978-0-1706733912-25417-9',
    publishers: ['Little-Allison', 'Martin Inc'],
    quantityAvailable: 43,
    price: 235240,
    summary: 'Various third thing ten class say inside.',
    averageRating: 3.5,
    genres: ['Fantasy'],
    reviews: ['Professor group trouble necessary.'],
  },
  {
    title: 'Upgradable logistical knowledgebase',
    authors: ['Samantha Nicholson', 'Jessica Russell'],
    ISBN: '978-0-1706733912-76712-9',
    publishers: ['Rodgers Group', 'Martin, Vega and Macias'],
    quantityAvailable: 44,
    price: 772316,
    summary:
      'Half our help PM. Own sign avoid all game economic hair indeed. Assume suffer much next tax beyond.',
    averageRating: 4.6,
    genres: ['Mystery', 'Biography'],
    reviews: [
      'Ready consumer report play task sort.',
      'Inside loss college cause defense again.',
    ],
  },
  {
    title: 'Monitored tangible hardware',
    authors: ['Carol Reynolds', 'Anthony Williams'],
    ISBN: '978-0-1706733912-82414-9',
    publishers: ['Smith, Henry and Bowen'],
    quantityAvailable: 45,
    price: 3439,
    summary:
      'Question nature meet ago security. Watch democratic new whole matter.',
    averageRating: 4.7,
    genres: ['Philosophy', 'Science Fiction'],
    reviews: ['Pull maybe tax safe manage.', 'Discuss why wonder.'],
  },
  {
    title: 'Enterprise-wide background database',
    authors: ['Jacob Moore'],
    ISBN: '978-0-1706733912-48359-9',
    publishers: ['Jones-Rosales'],
    quantityAvailable: 11,
    price: 885507,
    summary:
      'Now must what admit customer growth to month. Board Republican method improve avoid claim.',
    averageRating: 3.5,
    genres: ['Espionage', 'Science Fiction'],
    reviews: ['Law under since area.'],
  },
  {
    title: 'Implemented bottom-line forecast',
    authors: ['Gregory Grimes DVM'],
    ISBN: '978-0-1706733912-79239-9',
    publishers: ['Washington, Sullivan and Gregory'],
    quantityAvailable: 38,
    price: 257519,
    summary:
      'Address everyone large we. Represent institution step technology sister police everybody.',
    averageRating: 3.2,
    genres: ['Romance', 'Fantasy', 'Dark Fantasy'],
    reviews: ['Response war reach consumer discuss her.'],
  },
  {
    title: 'Secured neutral structure',
    authors: ['David Mitchell', 'Lori Lambert', 'Nicole Thompson'],
    ISBN: '978-0-1706733912-48464-9',
    publishers: ['Beck-Sharp'],
    quantityAvailable: 47,
    price: 27544,
    summary:
      'Suggest bank today yourself customer level back. Hard enjoy feel age source. Kind challenge between.',
    averageRating: 4.4,
    genres: ['Political Thriller', 'Cozy Mystery'],
    reviews: ['Court third late reduce and.'],
  },
  {
    title: 'Balanced even-keeled model',
    authors: ['Cory Howell'],
    ISBN: '978-0-1706733912-96623-9',
    publishers: ['Ford Ltd', 'Meyer Group'],
    quantityAvailable: 15,
    price: 304977,
    summary:
      'Indeed sea car within when. Today security education. Space thought fear conference debate.',
    averageRating: 4.6,
    genres: ['Space Opera', 'Fiction', 'Horror'],
    reviews: [
      'Police interesting rich easy Democrat way.',
      'Live nature check the.',
    ],
  },
  {
    title: 'Inverse dedicated leverage',
    authors: ['Michael Martinez Jr.', 'Sierra Hooper'],
    ISBN: '978-0-1706733912-17640-9',
    publishers: ['Stout, James and Archer'],
    quantityAvailable: 43,
    price: 210746,
    summary: 'Break kitchen camera may. Save TV style father east term visit.',
    averageRating: 3.9,
    genres: ['Paranormal', 'Horror', 'Romance'],
    reviews: [
      'Bed station some.',
      'Cell doctor throw around spend guess huge agree.',
    ],
  },
  {
    title: 'Horizontal multi-state workforce',
    authors: ['Carol Hall', 'Julia Bailey'],
    ISBN: '978-0-1706733912-40554-9',
    publishers: ['Mueller LLC'],
    quantityAvailable: 38,
    price: 780580,
    summary:
      'Market risk discussion seek month edge. Data professional manager.',
    averageRating: 4.2,
    genres: ['Supernatural', 'Thriller', 'Poetry'],
    reviews: [
      'Despite difference several meeting yourself.',
      'What away cost usually international fill.',
    ],
  },
  {
    title: 'User-friendly contextually-based support',
    authors: ['Andrea Ibarra'],
    ISBN: '978-0-1706733912-58090-9',
    publishers: ['Sullivan PLC', 'Johnson, Jones and Snow'],
    quantityAvailable: 14,
    price: 410540,
    summary: 'Those paper raise performance.',
    averageRating: 3.8,
    genres: ['Science Fiction Romance', 'Romantic Suspense', 'Urban Fantasy'],
    reviews: ['Your job less summer.'],
  },
  {
    title: 'Vision-oriented next generation core',
    authors: ['Brian Burnett', 'Jessica Clark', 'Katelyn Michael'],
    ISBN: '978-0-1706733912-75757-9',
    publishers: ['Kelly and Sons', 'Perkins-Harris'],
    quantityAvailable: 10,
    price: 769992,
    summary:
      'News near election kind short important. Attorney treat month international future candidate everybody. Its music dream TV guess ago world. Thus democratic sense room.',
    averageRating: 3.6,
    genres: ['Fantasy', "Women's Fiction", 'Travel'],
    reviews: ['Rock thing blue fall base inside.'],
  },
];
